server:
    context-path: /swagger-demo
    port: 8080

logging:
    level:
      ROOT: ERROR
      com:
          flywaydb: ERROR
          bobwares.demo.swagger.config: INFO
          bobwares.demo.swagger.SwaggerDemoApplication: INFO
       

# H2
spring:
  h2.console.enabled: true
  h2.console.path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
      database: H2
      show-sql: false
      hibernate.ddl-auto: none

