
CREATE TABLE  CUSTOMER (
ID DECIMAL(19,0)  NOT NULL PRIMARY KEY,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50)
);

CREATE SEQUENCE CUSTOMER_SEQ START WITH 100 MINVALUE 100 MAXVALUE 999999;

INSERT INTO PUBLIC.CUSTOMER VALUES (1, 'JOE', 'SMITH');
INSERT INTO CUSTOMER VALUES (2, 'JOHN', 'DOE');
INSERT INTO CUSTOMER VALUES (3, 'STEVE', 'JONES');
INSERT INTO CUSTOMER VALUES (4, 'CHAD', 'SMITH');
INSERT INTO CUSTOMER VALUES (5, 'ANTHONY', 'KIEDIS');
INSERT INTO CUSTOMER VALUES (6, 'JOHN', 'FRUCIATNE');
INSERT INTO CUSTOMER VALUES (7, 'MICHAEL', 'BALZARY');