
CREATE TABLE  CUSTOMER (
ID DECIMAL(19,0)  NOT NULL PRIMARY KEY,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50)
);

CREATE SEQUENCE CUSTOMER_SEQ START WITH 100 MINVALUE 100 MAXVALUE 9223372007;

INSERT INTO CUSTOMER (ID, FIRST_NAME, LAST_NAME) VALUES (1, 'JOE', 'SMITH');
INSERT INTO CUSTOMER (ID, FIRST_NAME, LAST_NAME) VALUES (2, 'JOHN', 'DOE');
INSERT INTO CUSTOMER (ID, FIRST_NAME, LAST_NAME) VALUES (3, 'STEVE', 'JONES');
COMMIT;